apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-aprd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-aprd@sha256:bc3e426d9819dbc0bbf9f711ed5fe5adde6e261ce7d3067292360119a7e8d4d1
        name: my-python
        resources: {}
status: {}
